### ISSUE TITLE
Venues

### ISSUE THREAD

**Issue by ecwyne** [MyDudes/austins-bachelor-party#2]
Here's a list of venues I've been looking at (ranked from most to least favorite). Let me know what you think! Prices are in $'s/night we would stay three nights.

1. ~~[$150 The Devore Arm Lodge](http://www.vrbo.com/708687)~~
2. [$190 Private hot tub, room for 18, huge deck!](http://www.vrbo.com/701776)
3. ~~[$250 Sunset Chalet - 2600 sq.ft. Multi-Seasonal](http://www.vrbo.com/263887)~~
4. ~~[$175 Deer House in Charleston](http://www.vrbo.com/306282)~~
5. ~~[$280 Emerald Island - Boat Access Only: Secluded](http://www.vrbo.com/701405)~~
6. ~~[$195 STORYBOOK COTTAGE NEAR LASSEN](http://www.vrbo.com/244546)~~

Feel free to add any other venues/ideas in a comment!

**Comment by keithtesterman** [comment]
http://www.vrbo.com/609247
just another idea I found

**Comment by Geocarcamo** [comment]
So here are my ideas: 

Ever since all of us Oregonians have known Austin, he has always talked so much about Houseboats and how it was a huge part of his life. Something that he always wanted us to participate in and experience with him. So my idea was we see about getting a houseboat for the weekend and get to live the life and go do some fun things as well while we are down there. plus last night out of nowhere he looked up water level of lake shasta. not sure if it was a hint but it reaffirmed my idea that i've had for a while. 

Also. the other thing that Austin is all about is making memories. So if we don't think that houseboating is a good idea, than my other thought is that we need to have a weekend full of a adventures. My idea was some rafting on the river, or something like that that is fun and we will remember doing. Something we haven't done together before.

**Comment by Geocarcamo** [comment]
http://www.vrbo.com/496062 

this one has a ping pong table and a hot tub. and would go more with my second idea.

**Comment by ecwyne** [comment]
@Geocarcamo I'm a HUGE fan of houseboating and I'm sure Austin would love that too.

I do have a couple concerns with houseboating:
- it would cost [$566/night](http://www.bridgebayhouseboats.com/houseboats/summit/) just for the houseboat (before food, drinks, launch fees etc.).
- We MIGHT fit in the smaller boat for [$450/night](http://www.bridgebayhouseboats.com/houseboats/cascade/) (It would be tight)
- Logistically it would be challenging to get everyone on the boat if we arrive at different times.
- Without another boat to go play on (ski/wakeboard/tube) it's really not terribly fun to just sit in the houseboat.

Does anyone in the group have access to a ski boat or jet skis? (That would also add additional cost for gas etc.)

**Comment by ecwyne** [comment]
@Geocarcamo that place looks awesome!! Just looking at it on my phone at lunch, I'll have to check it out more tonight. Great find!

**Comment by Geocarcamo** [comment]
So this is one month away! crazy! 

What does eveyone think of the places. we should probably  have this nailed down by next week where we are going (?)

**Comment by keithtesterman** [comment]
So I have another boat in response to the need for a second boat for house
boating. But that is quite expensive. That would be over 150 a person just
for the boat. Not to mention fuel for my boat which would probably be 300
for the weekend and Then food which for 11 people...5 or 6 meals would be
another 50 each plus alcohol. My guess is we would need to b3 ready to
spend 250 or 300 each.

So this is one month away! crazy!

What does eveyone think of the places. we should probably have this nailed
down by next week where we are going (?)

—
Reply to this email directly or view it on GitHub
<https://github.com/MyDudes/austins-bachelor-party/issues/2#issuecomment-105334347>
.

**Comment by ecwyne** [comment]
I'm feeling pretty set on either the top two from the original post or the one that @Geocarcamo posted ("Hiker's Paradise")

I'll reach out to the owners this week and see if they're all available for that weekend.

**Comment by jmanv** [comment]
hey guys! sorry i haven't responded, i thought my email would be doing a better job alerting me on postings haha. 
Ill take a look at the houses tomorrow when i get a sec and give my feedback!

**Comment by jmanv** [comment]
hey sorry, so doesn't look like my email did a good job letting me know you guys were talking on here, and i didnt realize i was responding to a post from a week ago! haha
what did you happen to find out, Eric?

**Comment by ecwyne** [comment]
@MyDudes/bachelorparty 
It's decided! We're headed to [Cogan Cabin](http://www.vrbo.com/701776)!
